### ISSUE TITLE
Publish release

### ISSUE THREAD

**Issue by tony** [zaproxy/actions-common#19]
Hi, thank you for the project!

#15 was merged in dc737b2, for specifying artifact name. The current actions-common release has it being hard-coded. It causes artifacts to be overwritten if multiple scans are in the same run.

This is needed for issue https://github.com/zaproxy/action-baseline/issues/45 (PR: https://github.com/zaproxy/action-baseline/pull/64)

There doesn't seem to be anything breaking: https://github.com/zaproxy/actions-common/compare/scans-v0.2.0...master

Since the param differs (but is a noop for current users if `artifactName` is unspecified), it may make sense to have this as `0.3.0`.

**Comment by erichiggins** [comment]
No new tag seems to have been created. Why was this marked as completed? It's still blocking https://github.com/zaproxy/action-baseline/issues/45 and https://github.com/zaproxy/action-baseline/pull/64

**Comment by kingthorin** [comment]
It wasn’t closed by the project team 🤷‍♂️

**Comment by tony** [comment]
@erichiggins @kingthorin Reopened

**Comment by erichiggins** [comment]
Thanks! Is there anything else needed to publish a new release?

**Comment by thc202** [comment]
Yes, there are ongoing PRs.

**Comment by nascit** [comment]
Any blockers for publishing a new release?

**Comment by kingthorin** [comment]
Time & team size.

**Comment by thc202** [comment]
Closing, there's a new version now available.

**Comment by thc202** [comment]
The actions will pick the new version through a @dependabot update.

**Comment by thc202** [comment]
I was wrong, @dependabot is only enabled for sec updates… will check that.
