### ISSUE TITLE
Update `@actions` packages throughout packages

### ISSUE THREAD

**Issue by tony** [zaproxy/actions-common#30]
I think it's a plus to use the latest stable versions of the [actions/toolkit](https://github.com/actions/toolkit) packages:

- [`@actions/artifact`](https://github.com/actions/toolkit/tree/main/packages/artifact) - [release notes](https://github.com/actions/toolkit/blob/main/packages/artifact/RELEASES.md)
- [`@actions/core`](https://github.com/actions/toolkit/tree/main/packages/core) - [release notes](https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md)
- [`@actions/exec`](https://github.com/actions/toolkit/tree/main/packages/exec) - [release notes](https://github.com/actions/toolkit/blob/main/packages/exec/RELEASES.md)
- [`@actions/github`](https://github.com/actions/toolkit/tree/main/packages/github) - [release notes](https://github.com/actions/toolkit/blob/main/packages/github/RELEASES.md)

**Comment by thc202** [comment]
The issue is not necessary if there's already a pull request.

**Comment by tony** [comment]
@thc202 Such as #18?  Can I close this then?

**Comment by thc202** [comment]
Yes.

**Comment by tony** [comment]
Closing per #18 being open as a pull request
